- name: 'ask to the BS team'
  description: 'We don't know this or this problem's solution. Ask this to the BS team on Twitter'
  color: 'f29686'
- name: 'help wanted'
  description: 'Extra attention is needed'
  color: '008672'
- name: 'inactive'
  description: 'This pr/issue is not active anymore (added after 7 days of inactivity)'
  color: 'd93f0b'
- name: 'not releated'
  description: 'Not releated to this package or Brawl Stars'
  color: '1d76db'
- name: 'priorty: high'
  description: 'This is important and we must work on this ASAP'
  color: 'b7ec00'
- name: 'priorty: low'
  description: 'This is not very important, actually it's not important at all (or a little little important).'
  color: 'b7ec00'
- name: 'priorty: medium'
  description: 'This is not very important (but its a little important).'
  color: 'b7ec00'
- name: 's: already fixed'
  description: 'This was already fixed before this pr/issue'
  color: '72e9fa'
- name: 's: BS API bug'
  description: 'This is a bug which is not from us, it's from the official Brawl Stars API'
  color: '72e9fa'
- name: 's: duplicate'
  description: 'This issue or pull request already exists'
  color: '72e9fa'
- name: 's: exists'
  description: 'Already exists in this package'
  color: '72e9fa'
- name: 's: invalid'
  description: 'This doesn't seem right'
  color: '72e9fa'
- name: 's: won't fix'
  description: 'This will not be worked on'
  color: '72e9fa'
- name: 'type: bug'
  description: 'Something isn't working'
  color: '24af6c'
- name: 'type: discussion'
  description: 'Discuss this pr/issue with us'
  color: '24af6c'
- name: 'type: idea'
  description: 'New feature or request'
  color: '24f6c'
- name: 'type: NEW'
  description: 'New version/update idea's issue or pull request'
  color: '24af6c'
- name: 'update: npm'
  description: 'Dependabot NPM updates'
  color: 'f73c6e'
- name: 'review: waiting'
  description: 'Waiting for a collaborator to review this pr'
  color: '7fdc4f'
- name: 'review: approved'
  description: 'This pr has been approved by a collaborator'
  color: '7fdc4f'
