name: VuePress

on:
  push:
    branches:
      - docs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Download
      run: npm i vue-discord-message@5.0.2 vuepress-theme-yuu@3.0.1 vuepress@1.8.2

    #- name: Build
     # run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./guide/.vuepress/dist
        publish_branch: pages
        destination_dir: ./guide/
