name: VuePress

on:
  push:
    branches:
      - docs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Install Node v16
      uses: actions/setup-node@v2
      with:
        node-version: 16
      
    - name: Download
      run: npm i

    - name: Build
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./guide/.vuepress/dist
        publish_branch: pages
        destination_dir: ./guide/
